#!/bin/sh
curl -C - -L -o public_Q0_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q0_public/public_Q0_long_1.tgz
curl -C - -L -o public_Q0_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q0_public/public_Q0_short_1.tgz
curl -C - -L -o public_Q10_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_10.tgz
curl -C - -L -o public_Q10_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_1.tgz
curl -C - -L -o public_Q10_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_2.tgz
curl -C - -L -o public_Q10_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_3.tgz
curl -C - -L -o public_Q10_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_4.tgz
curl -C - -L -o public_Q10_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_5.tgz
curl -C - -L -o public_Q10_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_6.tgz
curl -C - -L -o public_Q10_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_7.tgz
curl -C - -L -o public_Q10_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_8.tgz
curl -C - -L -o public_Q10_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_long_9.tgz
curl -C - -L -o public_Q10_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q10_public/public_Q10_short_1.tgz
curl -C - -L -o public_Q11_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_10.tgz
curl -C - -L -o public_Q11_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_1.tgz
curl -C - -L -o public_Q11_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_2.tgz
curl -C - -L -o public_Q11_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_3.tgz
curl -C - -L -o public_Q11_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_4.tgz
curl -C - -L -o public_Q11_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_5.tgz
curl -C - -L -o public_Q11_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_6.tgz
curl -C - -L -o public_Q11_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_7.tgz
curl -C - -L -o public_Q11_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_8.tgz
curl -C - -L -o public_Q11_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_long_9.tgz
curl -C - -L -o public_Q11_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q11_public/public_Q11_short_1.tgz
curl -C - -L -o public_Q12_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_1.tgz
curl -C - -L -o public_Q12_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_2.tgz
curl -C - -L -o public_Q12_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_3.tgz
curl -C - -L -o public_Q12_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_4.tgz
curl -C - -L -o public_Q12_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_5.tgz
curl -C - -L -o public_Q12_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_6.tgz
curl -C - -L -o public_Q12_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_7.tgz
curl -C - -L -o public_Q12_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_8.tgz
curl -C - -L -o public_Q12_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_long_9.tgz
curl -C - -L -o public_Q12_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q12_public/public_Q12_short_1.tgz
curl -C - -L -o public_Q13_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_10.tgz
curl -C - -L -o public_Q13_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_1.tgz
curl -C - -L -o public_Q13_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_2.tgz
curl -C - -L -o public_Q13_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_3.tgz
curl -C - -L -o public_Q13_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_4.tgz
curl -C - -L -o public_Q13_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_5.tgz
curl -C - -L -o public_Q13_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_6.tgz
curl -C - -L -o public_Q13_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_7.tgz
curl -C - -L -o public_Q13_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_8.tgz
curl -C - -L -o public_Q13_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_long_9.tgz
curl -C - -L -o public_Q13_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q13_public/public_Q13_short_1.tgz
curl -C - -L -o public_Q14_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_10.tgz
curl -C - -L -o public_Q14_long_11.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_11.tgz
curl -C - -L -o public_Q14_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_1.tgz
curl -C - -L -o public_Q14_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_2.tgz
curl -C - -L -o public_Q14_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_3.tgz
curl -C - -L -o public_Q14_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_4.tgz
curl -C - -L -o public_Q14_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_5.tgz
curl -C - -L -o public_Q14_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_6.tgz
curl -C - -L -o public_Q14_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_7.tgz
curl -C - -L -o public_Q14_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_8.tgz
curl -C - -L -o public_Q14_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_long_9.tgz
curl -C - -L -o public_Q14_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q14_public/public_Q14_short_1.tgz
curl -C - -L -o public_Q15_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_10.tgz
curl -C - -L -o public_Q15_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_1.tgz
curl -C - -L -o public_Q15_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_2.tgz
curl -C - -L -o public_Q15_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_3.tgz
curl -C - -L -o public_Q15_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_4.tgz
curl -C - -L -o public_Q15_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_5.tgz
curl -C - -L -o public_Q15_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_6.tgz
curl -C - -L -o public_Q15_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_7.tgz
curl -C - -L -o public_Q15_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_8.tgz
curl -C - -L -o public_Q15_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_long_9.tgz
curl -C - -L -o public_Q15_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q15_public/public_Q15_short_1.tgz
curl -C - -L -o public_Q16_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_10.tgz
curl -C - -L -o public_Q16_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_1.tgz
curl -C - -L -o public_Q16_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_2.tgz
curl -C - -L -o public_Q16_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_3.tgz
curl -C - -L -o public_Q16_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_4.tgz
curl -C - -L -o public_Q16_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_5.tgz
curl -C - -L -o public_Q16_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_6.tgz
curl -C - -L -o public_Q16_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_7.tgz
curl -C - -L -o public_Q16_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_8.tgz
curl -C - -L -o public_Q16_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_long_9.tgz
curl -C - -L -o public_Q16_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q16_public/public_Q16_short_1.tgz
curl -C - -L -o public_Q17_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q17_public/public_Q17_long_1.tgz
curl -C - -L -o public_Q17_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q17_public/public_Q17_long_2.tgz
curl -C - -L -o public_Q17_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q17_public/public_Q17_long_3.tgz
curl -C - -L -o public_Q17_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q17_public/public_Q17_long_4.tgz
curl -C - -L -o public_Q17_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q17_public/public_Q17_short_1.tgz
curl -C - -L -o public_Q1_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q1_public/public_Q1_long_1.tgz
curl -C - -L -o public_Q1_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q1_public/public_Q1_long_2.tgz
curl -C - -L -o public_Q1_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q1_public/public_Q1_long_3.tgz
curl -C - -L -o public_Q1_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q1_public/public_Q1_long_4.tgz
curl -C - -L -o public_Q1_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q1_public/public_Q1_short_1.tgz
curl -C - -L -o public_Q2_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_10.tgz
curl -C - -L -o public_Q2_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_1.tgz
curl -C - -L -o public_Q2_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_2.tgz
curl -C - -L -o public_Q2_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_3.tgz
curl -C - -L -o public_Q2_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_4.tgz
curl -C - -L -o public_Q2_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_5.tgz
curl -C - -L -o public_Q2_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_6.tgz
curl -C - -L -o public_Q2_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_7.tgz
curl -C - -L -o public_Q2_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_8.tgz
curl -C - -L -o public_Q2_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_long_9.tgz
curl -C - -L -o public_Q2_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q2_public/public_Q2_short_1.tgz
curl -C - -L -o public_Q3_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_10.tgz
curl -C - -L -o public_Q3_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_1.tgz
curl -C - -L -o public_Q3_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_2.tgz
curl -C - -L -o public_Q3_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_3.tgz
curl -C - -L -o public_Q3_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_4.tgz
curl -C - -L -o public_Q3_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_5.tgz
curl -C - -L -o public_Q3_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_6.tgz
curl -C - -L -o public_Q3_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_7.tgz
curl -C - -L -o public_Q3_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_8.tgz
curl -C - -L -o public_Q3_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_long_9.tgz
curl -C - -L -o public_Q3_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q3_public/public_Q3_short_1.tgz
curl -C - -L -o public_Q4_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_10.tgz
curl -C - -L -o public_Q4_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_1.tgz
curl -C - -L -o public_Q4_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_2.tgz
curl -C - -L -o public_Q4_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_3.tgz
curl -C - -L -o public_Q4_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_4.tgz
curl -C - -L -o public_Q4_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_5.tgz
curl -C - -L -o public_Q4_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_6.tgz
curl -C - -L -o public_Q4_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_7.tgz
curl -C - -L -o public_Q4_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_8.tgz
curl -C - -L -o public_Q4_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_long_9.tgz
curl -C - -L -o public_Q4_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q4_public/public_Q4_short_1.tgz
curl -C - -L -o public_Q5_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_10.tgz
curl -C - -L -o public_Q5_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_1.tgz
curl -C - -L -o public_Q5_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_2.tgz
curl -C - -L -o public_Q5_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_3.tgz
curl -C - -L -o public_Q5_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_4.tgz
curl -C - -L -o public_Q5_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_5.tgz
curl -C - -L -o public_Q5_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_6.tgz
curl -C - -L -o public_Q5_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_7.tgz
curl -C - -L -o public_Q5_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_8.tgz
curl -C - -L -o public_Q5_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_long_9.tgz
curl -C - -L -o public_Q5_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q5_public/public_Q5_short_1.tgz
curl -C - -L -o public_Q6_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_10.tgz
curl -C - -L -o public_Q6_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_1.tgz
curl -C - -L -o public_Q6_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_2.tgz
curl -C - -L -o public_Q6_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_3.tgz
curl -C - -L -o public_Q6_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_4.tgz
curl -C - -L -o public_Q6_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_5.tgz
curl -C - -L -o public_Q6_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_6.tgz
curl -C - -L -o public_Q6_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_7.tgz
curl -C - -L -o public_Q6_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_8.tgz
curl -C - -L -o public_Q6_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_long_9.tgz
curl -C - -L -o public_Q6_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q6_public/public_Q6_short_1.tgz
curl -C - -L -o public_Q7_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_10.tgz
curl -C - -L -o public_Q7_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_1.tgz
curl -C - -L -o public_Q7_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_2.tgz
curl -C - -L -o public_Q7_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_3.tgz
curl -C - -L -o public_Q7_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_4.tgz
curl -C - -L -o public_Q7_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_5.tgz
curl -C - -L -o public_Q7_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_6.tgz
curl -C - -L -o public_Q7_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_7.tgz
curl -C - -L -o public_Q7_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_8.tgz
curl -C - -L -o public_Q7_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q7_public/public_Q7_long_9.tgz
curl -C - -L -o public_Q8_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_1.tgz
curl -C - -L -o public_Q8_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_2.tgz
curl -C - -L -o public_Q8_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_3.tgz
curl -C - -L -o public_Q8_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_4.tgz
curl -C - -L -o public_Q8_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_5.tgz
curl -C - -L -o public_Q8_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_6.tgz
curl -C - -L -o public_Q8_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_7.tgz
curl -C - -L -o public_Q8_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_long_8.tgz
curl -C - -L -o public_Q8_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q8_public/public_Q8_short_1.tgz
curl -C - -L -o public_Q9_long_10.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_10.tgz
curl -C - -L -o public_Q9_long_11.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_11.tgz
curl -C - -L -o public_Q9_long_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_1.tgz
curl -C - -L -o public_Q9_long_2.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_2.tgz
curl -C - -L -o public_Q9_long_3.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_3.tgz
curl -C - -L -o public_Q9_long_4.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_4.tgz
curl -C - -L -o public_Q9_long_5.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_5.tgz
curl -C - -L -o public_Q9_long_6.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_6.tgz
curl -C - -L -o public_Q9_long_7.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_7.tgz
curl -C - -L -o public_Q9_long_8.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_8.tgz
curl -C - -L -o public_Q9_long_9.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_long_9.tgz
curl -C - -L -o public_Q9_short_1.tgz https://archive.stsci.edu/missions/kepler/lightcurves/tarfiles/Q9_public/public_Q9_short_1.tgz
